[package]
org = "signup_app"
name = "signup_backend"
version = "0.1.0"
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true
[[dependency]]
org = "ballerina"
name = "jwt"
version = "2.8.0"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "2.4.1"
